server:
  port: 10000
bank:
name: SDG-BANK-ADIL

spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
bankreg:
  port: 12000
  hostname: localhost
  
ba: ZE
