server:
  port: 10000
bank:
name: SDG-BANK-ADIL

sdg-mysql:
  port: 3333
  ip: 127.0.0.1
  db: sdg_bank
  
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
bankreg:
  port: 12000
  hostname: localhost
 
